/*
* Generated by cppsrc.sh
* On 2016-01-20 22:48:52,08
* by Paweu
*/
/*--END OF HEADER BLOCK--*/

#pragma once
#ifndef StreamReader_H
#define StreamReader_H

#include <thread>

namespace OrbitLogger {

class StreamReader {
public:
	StreamReader(FILE* Stream, LogChannel Channel);
	~StreamReader();
private:
	LogChannel m_Channel;
	bool m_ThreadCanRun;
	int fdOutPipe[2];
	int fdOut;

	void ThreadMain();
};

} //namespace OrbitLogger 

#endif
